<a href="https://colab.research.google.com/github/WardTurkyeh/ML-py/blob/main/OptimalModel_Hyperpara.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
from sklearn.datasets import load_digits

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.model_selection import GridSearchCV

In [17]:
digits = load_digits()
df = pd.DataFrame(digits.data)
df.head()

    0    1    2     3     4     5    6   ...   57   58    59    60    61   62   63
0  0.0  0.0  5.0  13.0   9.0   1.0  0.0  ...  0.0  6.0  13.0  10.0   0.0  0.0  0.0
1  0.0  0.0  0.0  12.0  13.0   5.0  0.0  ...  0.0  0.0  11.0  16.0  10.0  0.0  0.0
2  0.0  0.0  0.0   4.0  15.0  12.0  0.0  ...  0.0  0.0   3.0  11.0  16.0  9.0  0.0
3  0.0  0.0  7.0  15.0  13.0   1.0  0.0  ...  0.0  7.0  13.0  13.0   9.0  0.0  0.0
4  0.0  0.0  0.0   1.0  11.0   0.0  0.0  ...  0.0  0.0   2.0  16.0   4.0  0.0  0.0

[5 rows x 64 columns]

In [22]:
model_params = {
    'svm':{
        'model': svm.SVC(gamma='auto'),
        'params': {
            'C':[1,10,20],
            'kernel':['rbf', 'linear']
        }
    },
    'logistic_regression':{
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    },
    'decision_tree_classifier':{
        'model': DecisionTreeClassifier(),
        'params': {
            'min_samples_leaf': [1,5,10]
        }
    },
    'random_forest_classifier':{
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [1,5,10]
        }
    }


}

In [23]:
scores = []

for model_name,mp in model_params.items():
  clf=GridSearchCV(mp['model'],mp['params'], cv=5, return_train_score=False)
  clf.fit(df, digits.target)
  scores.append({
      'model': model_name,
      'best_score':clf.best_score_,
      'best_params':clf.best_params_
  })

In [24]:
scores_df = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
scores_df

                      model  best_score                   best_params
0                       svm    0.947697  {'C': 1, 'kernel': 'linear'}
1       logistic_regression    0.922114                      {'C': 1}
2  decision_tree_classifier    0.788022       {'min_samples_leaf': 1}
3  random_forest_classifier    0.895955          {'n_estimators': 10}